### ISSUE TITLE
Implement monitoring and observability features

### ISSUE THREAD

**Issue by Toasterson** [Toasterson/oxifed#10]
## Overview
Implement comprehensive monitoring and observability features to ensure the ActivityPub platform can be effectively operated, debugged, and optimized in production environments.

## Current State
The platform likely has basic logging but lacks the comprehensive monitoring, metrics collection, and observability features necessary for production operations, troubleshooting, and performance optimization.

### 1. Metrics Collection
- Application performance metrics (request latency, throughput, error rates)
- System resource metrics (CPU, memory, disk, network usage)
- ActivityPub federation metrics (delivery success rates, signature verification times)
- Database performance metrics (query times, connection pool usage)
- Message queue metrics (queue depth, processing rates, consumer lag)

### 2. Structured Logging
- Centralized logging with structured JSON format
- Log aggregation and searching capabilities
- Configurable log levels per component
- Request tracing and correlation IDs
- Security event logging and audit trails

### 3. Health Checks and Alerts
- Health check endpoints for all services
- Automated alerting for critical issues
- Service dependency monitoring
- Performance threshold monitoring
- Federation connectivity monitoring

### 4. Observability Dashboard
- Real-time system health dashboard
- Historical performance trends
- Federation status monitoring
- User activity analytics
- Error tracking and analysis

### 5. Distributed Tracing
- Request tracing across service boundaries
- ActivityPub message flow tracking
- Performance bottleneck identification
- Inter-service communication monitoring

### Metrics Infrastructure
```rust
// New monitoring modules
src/monitoring/
├── metrics/
│   ├── collector.rs     // Metrics collection framework
│   ├── counters.rs      // Counter metrics (requests, errors)
│   ├── histograms.rs    // Histogram metrics (latency, sizes)
│   ├── gauges.rs        // Gauge metrics (active connections, queue depth)
│   └── exporters/       // Metric export formats
│       ├── prometheus.rs
│       ├── influxdb.rs
│       └── statsd.rs
├── tracing/
│   ├── tracer.rs        // Distributed tracing setup
│   ├── spans.rs         // Span management
│   └── correlation.rs   // Request correlation IDs
├── health/
│   ├── checks.rs        // Health check framework
│   ├── endpoints.rs     // Health check HTTP endpoints
│   └── dependencies.rs  // Dependency health monitoring
└── alerts/
    ├── manager.rs       // Alert management
    ├── rules.rs         // Alert rule definitions
    └── channels.rs      // Alert delivery channels
```

### Metrics Framework
```rust
// Metrics collection framework
use prometheus::{Counter, Histogram, Gauge, Registry};

pub struct Metrics {
    // HTTP metrics
    pub http_requests_total: Counter,
    pub http_request_duration: Histogram,
    pub http_errors_total: Counter,
    
    // ActivityPub metrics
    pub activitypub_deliveries_total: Counter,
    pub activitypub_delivery_duration: Histogram,
    pub activitypub_signature_verifications: Counter,
    pub activitypub_signature_failures: Counter,
    
    // Database metrics
    pub db_query_duration: Histogram,
    pub db_connections_active: Gauge,
    pub db_query_errors: Counter,
    
    // Message queue metrics
    pub mq_messages_published: Counter,
    pub mq_messages_consumed: Counter,
    pub mq_queue_depth: Gauge,
    pub mq_consumer_lag: Histogram,
}

impl Metrics {
    pub fn new() -> Result<Self, Box<dyn std::error::Error>> {
        // Initialize all metrics with appropriate labels
    }
    
    pub fn register(&self, registry: &Registry) -> Result<(), Box<dyn std::error::Error>> {
        // Register all metrics with Prometheus registry
    }
}
```

### Structured Logging
```rust
// Enhanced logging configuration
use tracing::{info, error, warn, debug, span, Level, instrument};
use tracing_subscriber::{EnvFilter, fmt, layer::SubscriberExt};

#[derive(Debug)]
pub struct LogConfig {
    pub level: String,
    pub format: LogFormat,
    pub output: LogOutput,
    pub include_traces: bool,
}

pub enum LogFormat {
    Json,
    Pretty,
    Compact,
}

pub enum LogOutput {
    Stdout,
    File { path: PathBuf },
    Syslog,
    ElasticSearch { url: String },
}

// Request tracing middleware
#[instrument(skip(req), fields(request_id = %uuid::Uuid::new_v4()))]
pub async fn trace_requests<B>(req: Request<B>, next: Next<B>) -> Response {
    let start = Instant::now();
    let method = req.method().clone();
    let path = req.uri().path().to_string();
    
    let response = next.run(req).await;
    let duration = start.elapsed();
    
    info!(
        method = %method,
        path = %path,
        status = response.status().as_u16(),
        duration_ms = duration.as_millis(),
        "Request completed"
    );
    
    response
}
```

### Health Checks
```rust
// Health check framework
#[async_trait]
pub trait HealthCheck {
    async fn check(&self) -> HealthStatus;
    fn name(&self) -> &str;
    fn timeout(&self) -> Duration;
}

#[derive(Debug, Serialize)]
pub struct HealthStatus {
    pub status: Status,
    pub message: Option<String>,
    pub details: HashMap<String, serde_json::Value>,
    pub checked_at: DateTime<Utc>,
}

#[derive(Debug, Serialize)]
pub enum Status {
    Healthy,
    Degraded,
    Unhealthy,
}

// Database health check
pub struct DatabaseHealthCheck {
    db: Database,
}

#[async_trait]
impl HealthCheck for DatabaseHealthCheck {
    async fn check(&self) -> HealthStatus {
        match self.db.run_command(doc! { "ping": 1 }, None).await {
            Ok(_) => HealthStatus {
                status: Status::Healthy,
                message: Some("Database connection successful".to_string()),
                details: HashMap::new(),
                checked_at: Utc::now(),
            },
            Err(e) => HealthStatus {
                status: Status::Unhealthy,
                message: Some(format!("Database connection failed: {}", e)),
                details: HashMap::new(),
                checked_at: Utc::now(),
            },
        }
    }
    
    fn name(&self) -> &str { "database" }
    fn timeout(&self) -> Duration { Duration::from_secs(5) }
}
```

### Alert Management
```rust
// Alert configuration and management
#[derive(Debug, Clone)]
pub struct AlertRule {
    pub name: String,
    pub metric: String,
    pub condition: AlertCondition,
    pub threshold: f64,
    pub duration: Duration,
    pub severity: AlertSeverity,
    pub channels: Vec<AlertChannel>,
}

#[derive(Debug, Clone)]
pub enum AlertCondition {
    GreaterThan,
    LessThan,
    Equal,
    NotEqual,
}

#[derive(Debug, Clone)]
pub enum AlertSeverity {
    Critical,
    Warning,
    Info,
}

#[derive(Debug, Clone)]
pub enum AlertChannel {
    Email { to: Vec<String> },
    Slack { webhook_url: String },
    PagerDuty { integration_key: String },
    Webhook { url: String },
}
```

## Configuration
```toml
[monitoring]
enabled = true
metrics_port = 9090
health_check_port = 8080

[monitoring.metrics]
namespace = "oxifed"
include_build_info = true
collection_interval = "15s"

[monitoring.tracing]
enabled = true
service_name = "oxifed"
jaeger_endpoint = "http://localhost:14268/api/traces"
sample_rate = 0.1

[monitoring.logging]
level = "info"
format = "json"
output = "stdout"
include_source = true
include_target = true

[monitoring.health_checks]
enabled = true
interval = "30s"
timeout = "10s"
endpoint = "/health"

[monitoring.alerts]
enabled = true
check_interval = "1m"

[[monitoring.alerts.rules]]
name = "high_error_rate"
metric = "http_errors_total"
condition = "greater_than"
threshold = 10.0
duration = "5m"
severity = "warning"
channels = ["email", "slack"]

[[monitoring.alerts.rules]]
name = "database_connection_failure"
metric = "db_connections_active"
condition = "less_than"
threshold = 1.0
duration = "1m"
severity = "critical"
channels = ["email", "pagerduty"]
```

### domainservd Monitoring
- HTTP request metrics for ActivityPub endpoints
- WebFinger request tracking
- Signature verification performance
- Inbox processing metrics
- Health checks for database and message queue

### publisherd Monitoring
- Activity delivery success/failure rates
- Federation delivery latency
- Message queue consumption rates
- Retry attempts and failures
- Remote server response times

### Database Monitoring
- Query performance metrics
- Connection pool utilization
- Index usage statistics
- Replication lag (if applicable)
- Storage usage trends

### Message Queue Monitoring
- Queue depth and consumer lag
- Message processing rates
- Dead letter queue activity
- Connection health
- Memory usage

### Grafana Dashboards
- System overview dashboard
- ActivityPub federation dashboard
- Database performance dashboard
- Message queue dashboard
- Alert status dashboard

### Key Metrics to Display
- Request rate and latency percentiles
- Error rates by endpoint and service
- ActivityPub delivery success rates
- Database query performance
- Queue processing rates
- System resource utilization

### Critical Alerts
- Service unavailable (health check failures)
- Database connection failures
- High error rates (>5% for 5 minutes)
- Message queue failures
- Disk space critical (<10% free)

### Warning Alerts
- High response times (>1s for 95th percentile)
- ActivityPub delivery failures (>10% for 10 minutes)
- Database slow queries (>1s average)
- Queue depth growing (>1000 messages)
- Memory usage high (>80% for 15 minutes)

## Security Monitoring
- Failed authentication attempts
- Unusual activity patterns
- Signature verification failures
- Rate limiting triggers
- Access to sensitive endpoints

## Performance Monitoring
- Request throughput and latency trends
- Resource utilization over time
- Database performance trends
- Federation delivery performance
- Memory and CPU usage patterns

## Testing and Validation
- Synthetic monitoring for critical paths
- Load testing with metrics collection
- Alert rule testing and validation
- Dashboard functionality testing
- Observability stack reliability testing

## Acceptance Criteria
- [ ] Comprehensive metrics collection for all services
- [ ] Structured logging with request correlation
- [ ] Health check endpoints for all services
- [ ] Real-time monitoring dashboard
- [ ] Automated alerting for critical issues
- [ ] Distributed tracing for request flows
- [ ] Performance monitoring and trend analysis
- [ ] Security event monitoring and logging
- [ ] Documentation for monitoring setup and operations
- [ ] Integration with popular observability tools

## Performance Requirements
- Metrics collection overhead < 5% CPU usage
- Log ingestion rate > 10,000 events/second
- Alert delivery time < 2 minutes
- Dashboard load time < 3 seconds
- Tracing sampling overhead < 1% latency increase

## Tools and Dependencies
```toml
# Add to Cargo.toml
[dependencies]
prometheus = "0.13"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "json"] }
tracing-opentelemetry = "0.21"
opentelemetry = "0.20"
opentelemetry-jaeger = "0.19"
serde_json = "1.0"
tokio-metrics = "0.3"
```

### External Tools
- Prometheus for metrics storage
- Grafana for dashboards and visualization
- Jaeger or Zipkin for distributed tracing
- ELK Stack or Loki for log aggregation
- AlertManager for alert routing

## Documentation
- Monitoring architecture overview
- Metrics collection guide
- Dashboard setup instructions
- Alert configuration guide
- Troubleshooting runbook
- Performance tuning recommendations

## Labels
`monitoring`, `observability`, `metrics`, `logging`, `alerting`, `production-ready`
