### ISSUE TITLE
Add comprehensive integration tests

### ISSUE THREAD

**Issue by Toasterson** [Toasterson/oxifed#7]
## Overview
Implement comprehensive integration tests to ensure the ActivityPub platform works correctly with other federated servers and meets production quality standards.

## Current State
The platform likely has basic unit tests but lacks comprehensive integration testing that validates the entire system's behavior, federation capabilities, and interoperability with other ActivityPub implementations.

### 1. ActivityPub Federation Tests
- Test federation with real ActivityPub servers (Mastodon, Pleroma, PeerTube)
- Verify bidirectional communication (sending and receiving activities)
- Test all ActivityPub activity types (Create, Update, Delete, Follow, Like, Announce, etc.)
- Validate WebFinger discovery and actor resolution
- Test HTTP signature verification with different implementations

### 2. Multi-Domain Testing
- Test scenarios with multiple domains hosted on the same instance
- Verify domain isolation and configuration
- Test cross-domain interactions within the same instance
- Validate domain-specific settings and policies

### 3. End-to-End Workflow Tests
- Complete user registration and profile creation flows
- Publishing content and federated delivery
- Following/unfollowing actors across instances
- Social interactions (likes, boosts, replies) across federation
- Content moderation and blocking scenarios

### 4. Performance and Load Testing
- Concurrent user scenarios
- High-volume message processing
- Database performance under load
- RabbitMQ message queue performance
- Memory and CPU usage profiling

### 5. Failure and Recovery Testing
- Network partition scenarios
- Database connectivity issues
- Message queue failures
- Graceful degradation testing
- Data consistency validation after failures

### Test Infrastructure
```rust
// New test modules to create
tests/
├── integration/
│   ├── federation/
│   │   ├── mastodon_integration.rs
│   │   ├── pleroma_integration.rs
│   │   ├── peertube_integration.rs
│   │   └── generic_activitypub.rs
│   ├── workflows/
│   │   ├── user_onboarding.rs
│   │   ├── content_publishing.rs
│   │   ├── social_interactions.rs
│   │   └── moderation_flows.rs
│   ├── multi_domain/
│   │   ├── domain_isolation.rs
│   │   ├── cross_domain_interactions.rs
│   │   └── domain_management.rs
│   ├── performance/
│   │   ├── load_testing.rs
│   │   ├── concurrent_users.rs
│   │   └── message_throughput.rs
│   └── reliability/
│       ├── network_failures.rs
│       ├── database_failures.rs
│       └── recovery_scenarios.rs
└── fixtures/
    ├── test_actors.json
    ├── test_activities.json
    ├── test_domains.json
    └── mock_responses/
```

### Test Environment Setup
- Docker Compose setup for isolated test environments
- Test instances of Mastodon, Pleroma for federation testing
- Separate test databases and message queues
- Automated test data generation and cleanup
- Test key generation for cryptographic operations

#### Basic Federation
- Actor discovery via WebFinger
- Fetching actor profiles from remote instances
- Delivering activities to remote inboxes
- Receiving activities in local inboxes
- Signature verification with real ActivityPub servers

#### Social Interactions
- Following remote actors
- Unfollowing and handling Undo activities
- Liking remote posts
- Boosting/Announcing remote content
- Replying to remote posts
- Mentioning remote actors

#### Content Management
- Publishing public posts
- Publishing followers-only content
- Updating and deleting posts
- Handling content deletion across federation
- Media attachment handling

#### Load Testing Scenarios
```rust
// Example test structure
#[tokio::test]
async fn test_concurrent_activity_processing() {
    // Setup test environment
    // Generate 1000 concurrent activities
    // Measure processing time and resource usage
    // Validate all activities are processed correctly
}

#[tokio::test]
async fn test_high_volume_federation() {
    // Setup multiple remote test servers
    // Send 10,000 activities per minute
    // Measure delivery success rate
    // Validate memory and CPU usage stays within limits
}
```

#### Performance Benchmarks
- Process 1000 activities per second
- Handle 100 concurrent WebFinger requests
- Support 10,000 active users per instance
- Deliver federated messages within 30 seconds
- Database query response time < 100ms

### Test Data Management
- Automated generation of test actors and activities
- Realistic test data that covers edge cases
- Test data cleanup between test runs
- Fixtures for consistent test scenarios
- Mock server responses for external dependencies

### CI/CD Integration
```yaml
# GitHub Actions workflow example
name: Integration Tests
on: [push, pull_request]

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo:6.0
      rabbitmq:
        image: rabbitmq:3.11-management
      
    steps:
      - uses: actions/checkout@v3
      - name: Setup test environment
        run: docker-compose -f docker-compose.test.yml up -d
      - name: Run integration tests
        run: cargo test --test integration
      - name: Run federation tests
        run: cargo test --test federation
      - name: Performance benchmarks
        run: cargo test --test performance --release
```

### Test Configuration
```toml
# test-config.toml
[database]
url = "mongodb://localhost:27017/oxifed_test"

[rabbitmq]
url = "amqp://localhost:5672"

[federation]
test_instances = [
  "https://mastodon-test.example.com",
  "https://pleroma-test.example.com"
]

[performance]
max_concurrent_users = 1000
activity_rate_limit = 1000  # per second
test_duration = "5m"
```

### Unit Tests Enhancement
- Increase code coverage to >90%
- Test all error conditions and edge cases
- Mock external dependencies consistently
- Test cryptographic operations with known vectors

### Integration Tests
- End-to-end API testing
- Database integration testing
- Message queue integration testing
- External service integration (WebFinger, HTTP signatures)

### System Tests
- Full system deployment testing
- Multi-service coordination testing
- Configuration validation testing
- Monitoring and logging validation

### Acceptance Tests
- User story validation
- Business requirement compliance
- Performance requirement validation
- Security requirement testing

### Testing Frameworks
- `tokio-test` - Async testing utilities
- `mockito` - HTTP mocking (already in dev-dependencies)
- `testcontainers` - Container-based testing
- `criterion` - Performance benchmarking
- `proptest` - Property-based testing

### Test Infrastructure
- Docker and Docker Compose for test environments
- Test instances of ActivityPub servers
- Load testing tools (wrk, apache bench)
- Database migration testing tools

### Monitoring and Metrics
- Test execution time tracking
- Resource usage monitoring during tests
- Test result analytics and reporting
- Performance regression detection

## Acceptance Criteria
- [ ] Federation tests pass with Mastodon, Pleroma, and PeerTube
- [ ] All ActivityPub activity types are tested end-to-end
- [ ] Performance benchmarks are established and met
- [ ] Integration tests run automatically in CI/CD
- [ ] Test coverage exceeds 90% for core functionality
- [ ] Failure scenarios are tested and handled gracefully
- [ ] Multi-domain scenarios are thoroughly tested
- [ ] Load testing validates system capacity
- [ ] Security testing covers authentication and authorization
- [ ] Test documentation is comprehensive and maintainable

## Performance Targets
- Integration test suite completes in < 30 minutes
- Federation tests complete in < 15 minutes
- Load tests can simulate 1000+ concurrent users
- Memory usage during tests < 2GB
- All tests are deterministic and repeatable

## Documentation Requirements
- Test execution and setup instructions
- Federation testing guide with setup for test servers
- Performance testing methodology
- Troubleshooting guide for test failures
- Test coverage reporting and analysis

## Monitoring and Reporting
- Automated test result reporting
- Performance trend analysis
- Test failure notification system
- Code coverage tracking over time
- Integration with GitHub Actions for PR testing

## Labels
`testing`, `integration`, `federation`, `performance`, `quality-assurance`
